// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodels

import (
	"github.com/dehwyy/acheron/apps/nexus/internal/gql/scalars"
)

type Query struct {
}

type StreamRequest struct {
	ID    string `json:"id"`
	Frame int32  `json:"frame"`
}

type StreamResponse struct {
	Data scalars.Bytes `json:"data"`
	ID   string        `json:"id"`
}
