version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cryptobot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptobot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: cryptobot_bot
    environment:
      API_TOKEN: ${API_TOKEN}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cryptobot
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db

volumes:
  db_data:
